openapi: "3.0.0"
info:
  title: Super Deals
  version: "1.0"
tags:
  - name: deals
    description: Deals service
components:
  schemas:
    $ref: "./schemas/_index.yml"
servers:
  - url: https://ifq1hc035i.execute-api.us-east-1.amazonaws.com/prod
paths:
  /merchant/deals:
    post:
      tags:
        - deals
      description: Merchant can add a deal to his catalog
      requestBody:
        required: true
        description: The deal to add
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/DealFormSchema"
      responses:
        "200":
          description: Successfully added the deal
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - dealId
                properties:
                  message:
                    type: string
                    example: "Deal successfully added"
                  dealId:
                    type: string
                    example: "1yn5w7gKp8d7L2M3v4e5T9a6B"
