openapi: "3.0.0"
info:
  title: Super Deals
  version: "1.0"

tags:
  - name: deals
    description: Deals service

components:
  schemas:
    $ref: "./schemas/_index.yml"
  securitySchemes:
    basic:
      description: none
      type: http
      scheme: basic
    jwt:
      description: JWT bearer token descrpition
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - basic: []
  - jwt: []

paths:
  /merchants/{merchantId}/deals:
    post:
      summary: CreateDeal
      tags:
        - deals
      description: Merchant can add a deal to his catalog
      security:
        # []
        - jwt: []
      requestBody:
        required: true
        description: The deal to add
        content:
          application/json:
            schema:
              $ref: "./schemas/CreateDealForm.yml"
      responses:
        "200":
          description: Successfully added the deal
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - dealId
                properties:
                  message:
                    type: string
                    example: "Deal successfully added"
                  dealId:
                    type: string
                    example: "1yn5w7gKp8d7L2M3v4e5T9a6B"
