openapi: "3.0.0"
info:
  title: SuperDeals
  version: "1.0"

tags:
  - name: deals
    description: Deals service

components:
  schemas:
    $ref: "./schemas/_index.yml"

  securitySchemes:
    basic:
      description: Basic authentication with username and password
      type: http
      scheme: basic
    jwt:
      description: JWT bearer token
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - basic: []
  - jwt: []

paths:
  /merchants/sign-up:
    $ref: "./resources/merchants/sign-up.yml"

  /merchants/sign-in:
    $ref: "./resources/merchants/sign-in.yml"

  /merchants/{merchantId}/deals:
    $ref: "./resources/merchants/create-deal.yml"

x-amazon-apigateway-cors:
  allowOrigin: "*"
  allowHeaders:
    - Content-Type
  allowMethods:
    - "*"
