openapi: "3.0.0"
info:
  title: SuperDeals
  version: "1.0"

tags:
  - name: deals
    description: Deals service

components:
  schemas:
    $ref: "./schemas/_index.yml"

  # parameters:
  #   $ref: "./parameters/_index.yml"

  responses:
    $ref: "./responses/_index.yml"

  securitySchemes:
    basic:
      description: Basic authentication with username and password
      type: http
      scheme: basic
    jwt:
      description: JWT bearer token
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - basic: []
  - jwt: []

paths:
  # Accounts service
  /accounts/sign-up:
    $ref: "./resources/accounts/sign-up.yml"

  /accounts/sign-in:
    $ref: "./resources/accounts/sign-in.yml"

  /accounts/confirm-sign-up:
    $ref: "./resources/accounts/confirm-sign-up.yml"

  # Deals service
  /deals?merchantId={merchantId}:
    $ref: "./resources/deals/create-deal.yml"

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params:
    validateRequestParameters: true
    validateRequestBody: false
  body:
    validateRequestBody: true
    validateRequestParameters: false
  none:
    validateRequestBody: false
    validateRequestParameters: false

x-amazon-apigateway-request-validator: all

x-amazon-apigateway-cors:
  allowOrigin: "*"
  allowHeaders:
    - Content-Type
  allowMethods:
    - "*"

x-amazon-apigateway-binary-media-types:
  - image/jpeg
